SELECT * FROM flutter_prueba.tratamiento;

ALTER TABLE TRATAMIENTO DROP COLUMN fecha_inicio;
ALTER TABLE TRATAMIENTO DROP COLUMN fecha_final;
ALTER TABLE TRATAMIENTO ADD fecha_inicio DATE NOT NULL DEFAULT ((CURRENT_DATE));
ALTER TABLE TRATAMIENTO ADD fecha_final DATE DEFAULT NULL;